tech:
  instagram: true
  linkedin: true
  youtube: true
  x: true
  tiktok: true
  douyin: false
  rednote: false

robotics:
  instagram: true
  linkedin: true
  youtube: true
  x: true
  tiktok: true
  douyin: true
  rednote: false

culture:
  instagram: true
  linkedin: false
  youtube: false
  x: false
  tiktok: true
  douyin: true
  rednote: true

biz:
  instagram: false
  linkedin: true
  youtube: true
  x: true
  tiktok: false
  douyin: false
  rednote: false

cn:
  instagram: false
  linkedin: false
  youtube: true
  x: false
  tiktok: true
  douyin: true
  rednote: true

meta:
  instagram: false
  linkedin: true
  youtube: false
  x: true
  tiktok: false
  douyin: false
  rednote: false
